Repository projectceladon/vendor-intel-utils-vertical-iot, pull requests merged in 2025-09, with the labels that each got.

#126 Upgrade to TWL Android kernel version v6.12.47
  bsp_diff/caas/device/intel/mixins/0002-Add-6.12-kernel-config.patch
  bsp_diff/caas/device/intel/mixins/0017-Enable-Type-C-Dual-Role-on-TWL.patch
  bsp_diff/caas/device/intel/project-celadon/0001-Add-6.12-kernel-config.patch
Labels: Valid commit message, Developer Approved, Pending PR Review, Engineering Build Successful

#125 Enable trusty and revert kernelflinger workaround
  bsp_diff/caas/device/intel/mixins/0026-Enable-trusty-on-android-15-kernel.patch
  bsp_diff/caas/hardware/intel/kernelflinger/0001-Revert-kernelflinger-patch.patch
Labels: Valid commit message, PR approved, Pending Developer Approval, Engineering Build Not Started

#128 Fix android build issue with new kernel 6.12.47
  bsp_diff/caas/device/intel/mixins/0004-Update-kernel-defconfig-6.12.patch
  bsp_diff/caas/device/intel/mixins/0016-TWL-Fix-kernel-config-kernel-6.12.40-errors.patch
Labels: Valid commit message, Developer Approved, PR approved, Engineering Build Successful
